name: Update Tournaments
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-back-to-back: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm start
        env:
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
